function output_finalpoints_paints(experimentDir,experimentLabel,experimentName,position,finalpoints_paints)
% function to output the data as organized format in a csv file
% Optimized for 100k DNA seqFISH+ analysis
% Input should be from the decoding script
% Date: 01/01/2021
% Author: Yodai Takei

for ch = 1:size(finalpoints_paints,2) % channel
    listSavePath = fullfile(experimentDir,'analysis',experimentLabel,'paint decoding',[experimentName '-output-finalpoints-paints-pos' num2str(position) '-ch' num2str(ch) '.csv']);
    fileID = fopen(listSavePath,'w');
    fprintf(fileID,'%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s\n', ...
                'fov', 'hyb','channel', 'cellID', 'x', 'y', 'z', 'dot_int',...
                'paint_int_1_1', 'paint_int_1_2','paint_int_1_3','paint_int_1_4','paint_int_1_5','paint_int_1_6',...
                'paint_int_1_7', 'paint_int_1_8','paint_int_1_9',...
                'paint_int_2_1', 'paint_int_2_2','paint_int_2_3','paint_int_2_4','paint_int_2_5','paint_int_2_6',...
                'paint_int_2_7', 'paint_int_2_8','paint_int_2_9',...
                'paint_int_3_1', 'paint_int_3_2','paint_int_3_3','paint_int_3_4','paint_int_3_5','paint_int_3_6',...
                'paint_int_3_7', 'paint_int_3_8','paint_int_3_9',...
                'paint_int_4_1', 'paint_int_4_2','paint_int_4_3','paint_int_4_4','paint_int_4_5','paint_int_4_6',...
                'paint_int_4_7', 'paint_int_4_8','paint_int_4_9');
    
    for hyb = 1:size(finalpoints_paints,1)

        for dot = 1:size(finalpoints_paints{hyb,ch}.cellID,1)
            
            if finalpoints_paints{hyb,ch}.cellID(dot) > 0
               cellID = finalpoints_paints{hyb,ch}.cellID(dot);
               x = finalpoints_paints{hyb,ch}.channels(dot,1);
               y = finalpoints_paints{hyb,ch}.channels(dot,2);
               z = finalpoints_paints{hyb,ch}.channels(dot,3);
               int = finalpoints_paints{hyb,ch}.intensity(dot);

                % print each line
                fprintf(fileID,'%.0f,%.0f,%.0f,%.0f,%.3f,%.3f,%.3f,%.0f,%.3f,%.3f,%.3f,%.3f,%.3f,%.3f,%.3f,%.3f,%.3f,%.3f,%.3f,%.3f,%.3f,%.3f,%.3f,%.3f,%.3f,%.3f,%.3f,%.3f,%.3f,%.3f,%.3f,%.3f,%.3f,%.3f,%.3f,%.3f,%.3f,%.3f,%.3f,%.3f,%.3f,%.3f,%.3f,%.3f\n',...
                    position, hyb, ch, cellID, x, y, z, int,...
                    finalpoints_paints{hyb,ch}.intensitypaint(dot,1),finalpoints_paints{hyb,ch}.intensitypaint(dot,2),...
                    finalpoints_paints{hyb,ch}.intensitypaint(dot,3),finalpoints_paints{hyb,ch}.intensitypaint(dot,4),...
                    finalpoints_paints{hyb,ch}.intensitypaint(dot,5),finalpoints_paints{hyb,ch}.intensitypaint(dot,6),...
                    finalpoints_paints{hyb,ch}.intensitypaint(dot,7),finalpoints_paints{hyb,ch}.intensitypaint(dot,8),...
                    finalpoints_paints{hyb,ch}.intensitypaint(dot,9),finalpoints_paints{hyb,ch}.intensitypaint(dot,10),...
                    finalpoints_paints{hyb,ch}.intensitypaint(dot,11),finalpoints_paints{hyb,ch}.intensitypaint(dot,12),...
                    finalpoints_paints{hyb,ch}.intensitypaint(dot,13),finalpoints_paints{hyb,ch}.intensitypaint(dot,14),...
                    finalpoints_paints{hyb,ch}.intensitypaint(dot,15),finalpoints_paints{hyb,ch}.intensitypaint(dot,16),...
                    finalpoints_paints{hyb,ch}.intensitypaint(dot,17),finalpoints_paints{hyb,ch}.intensitypaint(dot,18),...
                    finalpoints_paints{hyb,ch}.intensitypaint(dot,19),finalpoints_paints{hyb,ch}.intensitypaint(dot,20),...
                    finalpoints_paints{hyb,ch}.intensitypaint(dot,21),finalpoints_paints{hyb,ch}.intensitypaint(dot,22),...
                    finalpoints_paints{hyb,ch}.intensitypaint(dot,23),finalpoints_paints{hyb,ch}.intensitypaint(dot,24),...
                    finalpoints_paints{hyb,ch}.intensitypaint(dot,25),finalpoints_paints{hyb,ch}.intensitypaint(dot,26),...
                    finalpoints_paints{hyb,ch}.intensitypaint(dot,27),finalpoints_paints{hyb,ch}.intensitypaint(dot,28),...
                    finalpoints_paints{hyb,ch}.intensitypaint(dot,29),finalpoints_paints{hyb,ch}.intensitypaint(dot,30),...
                    finalpoints_paints{hyb,ch}.intensitypaint(dot,31),finalpoints_paints{hyb,ch}.intensitypaint(dot,32),...
                    finalpoints_paints{hyb,ch}.intensitypaint(dot,33),finalpoints_paints{hyb,ch}.intensitypaint(dot,34),...
                    finalpoints_paints{hyb,ch}.intensitypaint(dot,35),finalpoints_paints{hyb,ch}.intensitypaint(dot,36));
            end

        end

    end
    fclose(fileID);
end
